spring:
  application:
    name: Automated-CV-Monitoring
  profiles:
    active: local
  ai:
    openai:
      api-key:
      chat:
        options:
          model: gpt-4.1-mini
google:
  oauth:
    redirect-uri:
    success-redirect-uri:
    downloads-dir:
    client-secrets-file: classpath:google-secret.json

resume:
    storage:
        base-directory: